#!/bin/sh

alias cdtv="cd $PWD"

GCC_INSTALL_PATH="$HOME/products/gcc-c++-concepts"
export GCC_INSTALL_PATH

ORIGIN_INSTALL_PATH="$HOME/src/origin"
export ORIGIN_INSTALL_PATH

PATH="$GCC_INSTALL_PATH/bin:$PATH"
export PATH
LD_LIBRARY_PATH="$GCC_INSTALL_PATH/lib32:$LD_LIBRARY_PATH"
LD_LIBRARY_PATH="$GCC_INSTALL_PATH/lib64:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH
